version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common:
  &minio-common
  image: quay.io/minio/minio:RELEASE.2022-01-28T02-28-16Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
    MINIO_BROWSER_REDIRECT_URL: "http://localhost:9000"
    MINIO_SERVER_URL: "http://localhost:9000"
  healthcheck:
    test:
      [
        "CMD",
        "curl",
        "-f",
        "http://localhost:9000/minio/health/live"
      ]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  db:
    build:
      context: ../
      dockerfile: ./compose/database/Dockerfile
    container_name: db
    tty: true
    expose:
      - 1433
    restart: unless-stopped
    environment:
      SA_PASSWORD: "SqlServer2202Pass"
      ACCEPT_EULA: "Y"

  mediarapi:
    build:
      context: ../
      dockerfile: ./compose/api/Dockerfile
    container_name: mediarapi
    restart: unless-stopped
    environment:
      - TZ=Europe/Kiev
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - "db"
      - "nginx_minio"

  nginx_proxy:
    image: nginx:latest
    container_name: mediar_nginx_proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes_from:
      - teamcity_teamcity-agent_1:rw
    volumes:
      - ./nginx-proxy/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - mediarapi

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx_minio:
    image: nginx:1.19.2-alpine
    hostname: nginx_minio
    volumes_from:
      - teamcity_teamcity-agent_1:rw
    volumes:
      - ./minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
